# Site settings
title: GRPosh
description: 'We are the Grand Rapids Michigan PowerShell User Group. Join the Slack Team to find out more about events and meet other local PowerShellers.'
url: 'https://grposh.github.io'
baseurl: ''
google_analytics: 'UA-76450394-1'
disqus: 'GRPosh'

author:
  name: GRPosh
  email: grposh@outlook.com
  slack_team: GRPosh
  twitter_username: grposh
  github_username:  GRPosh
  youtube_channel: https://www.youtube.com/channel/UCb9jg2gj9alnFVCXuRuEVaA

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
future: True
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
