# Site settings
title: GRPosh
description: 'We are the Grand Rapids Michigan PowerShell User Group. Join the Slack Team to find out more about events and meet other local PowerShellers.'
url: 'http://grposh.github.io'
baseurl: '/'
google_analytics: 'UA-76450394-1'
# disqus_shortname: 'your-disqus-name'

author:
  name: GRPosh
  email: grposh@outlook.com
  slack_team: grposh
  twitter_username: grposh
  #facebook_username: joshgerdes
  github_username:  grposh
  #linkedin_username:  joshgerdes

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
